name: iOS - Build CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build & Test
    runs-on: macos-latest   

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: swifty-code-coverage
        uses: michaelhenry/swifty-code-coverage@v1.0.1
