name: iOS - Build CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      
      - name: Run tests
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
            project: Grocery Guru.xcodeproj
            scheme: Grocery Guru
            derived-data-path: ./output
            destination: "OS=14.4,name=iPhone 12 Pro"
            action: test
            enable-code-coverage: true

      - name: Test Coverage
        uses: maxep/xcodebuild-lcov-action@0.1.0
        with:
            derived-data-path: ./output
            target: Grocery Guru.app
            output-file: ./output/lcov.info
