name: iOS Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Build
        run: |
          set -o pipefail && \
          xcodebuild build-for-testing \
            -scheme "Grocery Guru Debug" \
            -project "Grocery Guru.xcodeproj" \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro" \
          | xcbeautify

      - name: Test
        run: |
          set -o pipefail && \
          xcodebuild test-without-building \
            -scheme "Grocery Guru Debug" \
            -project "Grocery Guru.xcodeproj" \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro" \
            -enableCodeCoverage YES \
            -resultBundlePath CoverageResults.xcresult \
          | xcbeautify

      - name: Export Coverage Report (JSON)
        run: |
          xcrun xccov view --report --json CoverageResults.xcresult > test_coverage.json

      - name: Export Coverage Report (Plain Text)
        run: |
          xcrun xccov view --report CoverageResults.xcresult > test_coverage.txt

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            test_coverage.json
            test_coverage.txt
